name: Deploy Webpack PWA to GitHub Pages

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main

  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add steps to install node.js and npm if not already installed
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install dependencies and build the PWA with webpack
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      # Store the built artifacts
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Restore the built artifacts
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      # Deploy the built artifacts to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
